@startuml
title  Resource diagram

object User {
  link: /api/users/:id
  id
  accounts: [Account]
  transactions : [Transaction]
  allows: GET, OPTIONS
}


object Account {
  link: /api/accounts/:id
  id
  user: User
  transactions: [Transaction]
  amount: Amount
  allows: GET, OPTIONS
}

object Transaction {
  link: /api/transactions/:id
  id
  from: Account
  to: Account
  amount: Amount
  status: Status
  allows: GET, POST, DELETE, OPTIONS
}

class Status {
  Open
  Processing
  Processed
  Closed
}

User --{ Account
User --{ Transaction

Account --{ Transaction

object Error {
  responseCode: int
  requestPath: String
  errorMessage: String
}
@enduml